# Generated by Django 4.2.3 on 2023-08-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='product_owner',
            new_name='product',
        ),
    ]
